name: Docker Image CI

on:
  push:
    branches:
    - main
    - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy the docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: web
        username: ${{ secrets.DO_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_PASSWORD }}
        registry: registry.digitalocean.com/safeops-challenge
        dockerfile: Dockerfile
        tags: ${{ github.sha }}, latest

  deploy-dev:
    environment: Dev
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Update deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: set image deployment web web=registry.digitalocean.com/safeops-challenge/web:${{ github.sha }} -n dev
        
  tests:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
    - uses: actions/checkout@v3
      with:
        repository: safeops-challenge/tests
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tests
      run: python -m pytest web_tests/
      env:
        INGRESS_URL: ${{ secrets.INGRESS_URL }}

        
  deploy-prod:
    environment: Prod
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Update deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: set image deployment web web=registry.digitalocean.com/safeops-challenge/web:${{ github.sha }} -n prod
        