name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy the docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: web
        username: ${{ secrets.DO_TOKEN }}
        password: ${{ secrets.DO_REGISTRY_PASSWORD }}
        registry: registry.digitalocean.com/safeops-challenge
        dockerfile: Dockerfile
        tags: ${{ github.sha }}, latest
  kube:
    runs-on: ubuntu-latest
    steps:
    - name: Update deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods -n app
        
        
